### PR TITLE
Refactoring, short-circuiting

### PR DESCRIPTION
**Pull request by lorensr**
Not ready to merge, I haven't tested yet. Probably even has syntax errors 😜 

Changes are more intelligible if you look at individual commits.
- In general when I've seen calling something not production-ready, it's sort of a vague unsubstantiated insult. Like the big firm that told me Meteor 0.9 wasn't production ready. Of course it was. So I think it's better to instead say why you're better, and that's more options and launch screen UX.
- tells them what they can do with pkg before getting into api
- ToC
- get them to use `Reloader.reload()` so we can keep `reloaderWasRefreshed` accurate.
- `launchScreenDelay`
- moved functions into Reloader for semantics and ability to use `this`, and now it's easier to see what's going on at the top level at the bottom of the file
- minor DRYing
- i'd recommend being more sparing with comments, in favor of writing readable code 😊 for example, i believe this:

``` javascript
// Hold the launch screen
const handle = LaunchScreen.hold();

// Just release the splash screen
handle.release();
```

takes longer to read and understand than this:

``` javascript
const launchScreen = LaunchScreen.hold();

launchScreen.release();
```

a lot of readbility has to do with naming and structure (`handle` -> `launchScreen`). similarly, note how I extracted out pieces of code, or compound booleans, into functions with names that were descriptive enough that no comment was necessary.

### CODE REVIEW

**Comment by lorensr** [comment]
Did your test app have much in it, or just a call to `configure` that you manually changed during testing?

**Comment by jamielob** [comment]
This looks great @lorensr! I'll take a better look tomorrow.    Test app was just a manual testing app.

**Comment by lorensr** [comment]
tests don't work, waiting on https://github.com/meteor/guide/issues/401

**Comment by lorensr** [comment]
actually probably a different problem: 
http://stackoverflow.com/questions/36855256/what-could-cause-an-onuse-package-to-not-be-defined-during-a-package-test

**Comment by lorensr** [comment]
tests working, would you like to add to them?

**Comment by lorensr** [comment]
_production-ready_ packages have tests and changelogs 😉 😄 good thing we're past 1.3 and don't have to use tinytest! https://github.com/lorensr/login-links/blob/master/tests/client/connectionLogin.js

**Comment by jamielob** [comment]
You're a star! I'm just finishing up some contract work and merging all this is next on my list.

**Comment by lorensr** [comment]
Thanks! It was enough changes that I wouldn't publish until more tests are written or it's re-manually tested

**Pull request merged**
